In [4]:
#https://towardsdatascience.com/demystifying-confusion-matrix-confusion-9e82201592fd
#Skipping the necessary Libraries import
#Reading the Data File
import pandas as pd
df = pd.read_csv('Result1.csv')
df.head(5)

Negative   Neutral  Positive  Sentiment Score  Class
0     0.218     0.345     0.437            0.219      3
1     0.000     1.000     0.000            0.000      2
2     0.000     1.000     0.000            0.000      2
3     0.000     0.571     0.429            0.429      3
4     0.608     0.392     0.000           -0.608      1

In [5]:
#To check if the data is equally balanced between the target classes
df['Class'].value_counts()

2    631
3     68
1     52
Name: Class, dtype: int64

In [6]:
#Defining features and target variable
from sklearn.model_selection import train_test_split
#from sklearn.cross_validation import train_test_split
y = df['Class'] #target variable we want to predict 
X = df.drop(columns = ['Class']) #set of required features, in this case all
#Splitting the data into train and test set 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [7]:
#Predicting using Logistic Regression for Binary classification 
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LR.fit(X_train,y_train) #fitting the model 
y_pred = LR.predict(X_test) #prediction

In [8]:
#Evaluation of Model - Confusion Matrix Plot
import numpy as np
import itertools
from matplotlib import pyplot as plt
from sklearn.metrics import confusion_matrix
def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    print(cm)

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.ylabel('True label')
    plt.xlabel('Predicted label')
    plt.tight_layout()


# Compute confusion matrix
cnf_matrix = confusion_matrix(y_test, y_pred)
print(cnf_matrix)
'''np.set_printoptions(precision=2)
# Plot non-normalized confusion matrix
plt.figure()
plot_confusion_matrix(cnf_matrix, classes=['Forged','Authorized'],
                      title='Confusion matrix, without normalization')'''


#extracting true_positives, false_positives, true_negatives, false_negatives
'''tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
print("True Negatives: ",tn)
print("False Positives: ",fp)
print("False Negatives: ",fn)
print("True Positives: ",tp)'''
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, y_pred))
print("=== Classification Report ===")
print(classification_report(y_test, y_pred))
print("=== Acurracy Score ===")
print( accuracy_score(y_test, y_pred))

[[ 15   2   0]
 [  0 157   0]
 [  0   0  14]]
=== Confusion Matrix ===
[[ 15   2   0]
 [  0 157   0]
 [  0   0  14]]
=== Classification Report ===
              precision    recall  f1-score   support

           1       1.00      0.88      0.94        17
           2       0.99      1.00      0.99       157
           3       1.00      1.00      1.00        14

    accuracy                           0.99       188
   macro avg       1.00      0.96      0.98       188
weighted avg       0.99      0.99      0.99       188

=== Acurracy Score ===
0.9893617021276596
