In [2]:
import pandas as pd
import numpy as np
dataset=pd.read_csv('Result1.csv')
# Number of rows and columns in dataset
dataset.shape

(751, 5)

In [3]:
print(dataset.describe())

         Negative     Neutral    Positive  Sentiment Score       Class
count  751.000000  751.000000  751.000000       751.000000  751.000000
mean     0.046667    0.899577    0.053754         0.007087    2.021305
std      0.171058    0.238677    0.176707         0.253001    0.399431
min      0.000000    0.000000    0.000000        -1.000000    1.000000
25%      0.000000    1.000000    0.000000         0.000000    2.000000
50%      0.000000    1.000000    0.000000         0.000000    2.000000
75%      0.000000    1.000000    0.000000         0.000000    2.000000
max      1.000000    1.000000    1.000000         1.000000    3.000000


In [8]:
#Target
Y = np.array(dataset['Class'])
#Features
X=dataset.drop('Class', axis=1)

In [5]:
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20)
from sklearn.svm import SVC
svcclassifier = SVC(kernel='linear')
svcclassifier.fit(X_train,Y_train)
print(X_train)
print(Y_train)
print(X_test)
print(Y_test)

     Negative   Neutral  Positive  Sentiment Score
625     0.000     0.455     0.545            0.545
647     0.000     1.000     0.000            0.000
70      0.000     1.000     0.000            0.000
450     0.000     1.000     0.000            0.000
18      0.000     1.000     0.000            0.000
44      0.000     0.263     0.737            0.737
42      0.000     0.500     0.500            0.500
742     0.000     0.357     0.643            0.643
444     0.000     1.000     0.000            0.000
58      0.756     0.244     0.000           -0.756
348     0.000     0.312     0.688            0.688
415     0.000     1.000     0.000            0.000
398     0.000     1.000     0.000            0.000
725     0.000     1.000     0.000            0.000
153     0.000     1.000     0.000            0.000
467     0.000     1.000     0.000            0.000
81      0.697     0.303     0.000           -0.697
399     0.000     1.000     0.000            0.000
63      0.744     0.256     0.0

In [6]:
Y_pred= svcclassifier.predict(X_test)
print(Y_pred)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 1 2 2 1 2 2 2 2 2 3 2 2 2 2 3 2
 2 2 2 2 2 2 2 2 2 3 2 2 2 2 2 2 2 2 2 2 2 2 3 2 2 2 2 2 2 2 2 2 2 2 1 2 2
 3 2 2 2 2 1 2 2 2 2 3 2 1 2 2 2 2 1 2 2 2 2 2 2 2 3 2 2 3 2 3 2 1 2 1 2 1
 2 2 2 1 2 2 2 2 2 2 2 2 2 2 3 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 2 2 2
 2 2 2]


In [7]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("=== Confusion Matrix ===")
print(confusion_matrix(Y_test, Y_pred))
print("=== Classification Report ===")
print(classification_report(Y_test, Y_pred))
print("=== Acurracy Score ===")
print( accuracy_score(Y_test, Y_pred))


=== Confusion Matrix ===
[[ 12   0   0]
 [  0 128   0]
 [  0   0  11]]
=== Classification Report ===
             precision    recall  f1-score   support

          1       1.00      1.00      1.00        12
          2       1.00      1.00      1.00       128
          3       1.00      1.00      1.00        11

avg / total       1.00      1.00      1.00       151

=== Acurracy Score ===
1.0
